### ISSUE TITLE
only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by Chang-007** [ICEORY/PMF#20]
Thank you very much for your work， and I am getting errors like this during training：
`only one element tensors can be converted to Python scalars`
![0582950fbc7fdecb442b400e201b66e](https://user-images.githubusercontent.com/55450113/188634031-087bbb18-c9b3-4197-9053-f90229868439.jpg)

It can be trained normally at the beginning, but this error is reported after a few hundred iters. Have you ever met? HELP

**Comment by iris0329** [comment]
Hmm, that's werid, can you print the value of `loss_lov.item()` and `input_feature.size(0)`.

A quickly suggestion is to commented [this line](https://github.com/ICEORY/PMF/blob/master/tasks/pmf/trainer.py#L400), because it's just for a logger of loss value, it won't effect the training process.

Best
